"use client";

import { Protected } from "@/components/app-shell";
import { Badge, Button, Card, Empty, Field, Skeleton } from "@/components/ui";
import { api, errorMessage, money } from "@/lib/api";
import type { AgentReply, AgentRecommendation } from "@/lib/agent";
import { Activity, BookmarkCheck, BrainCircuit, Check, CircleAlert, Gauge, ListChecks, Orbit, Pause, Play, Sparkles, Target, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type ActionItem = { id: string; title: string; reason: string; expected_impact: string; risk: string; review_trigger: string; priority: string; status: string; source: string };
type Overview = { score: string; score_label: string; score_explanation: string; factors: Array<{ code: string; name: string; score: string; max_score: string; value: string; interpretation: string }>; alerts: Array<{ level: string; code: string; title: string; detail: string }>; data_availability: { has_snapshot: boolean; snapshot_count: number; has_cashflow: boolean; goal_count: number }; cashflow_source?: { monthly_income_cny: string; monthly_fixed_expenses_cny: string; monthly_safety_buffer_cny: string }; actions: ActionItem[] };
type AllocationResult = { plan: { monthly_available_cny: string; monthly_allocated_cny: string; monthly_unallocated_cny: string; strategy: string; deadline_conflict_count: number; allocations: Array<{ goal_id: string; goal_name: string; gap_cny: string; monthly_allocation_cny: string; required_monthly_cny?: string; projected_months?: number; projected_completion_date?: string; due_date?: string; on_track?: boolean | null }> }; agent: AgentReply; overview: Overview };

function IntelligenceContent() {
  const [overview, setOverview] = useState<Overview | null>(null);
  const [result, setResult] = useState<AllocationResult | null>(null);
  const [budget, setBudget] = useState({ monthly_income_cny: "", monthly_fixed_expenses_cny: "", monthly_safety_buffer_cny: "", strategy: "BALANCED", provider: "auto" });
  const [loading, setLoading] = useState(true);
  const [planning, setPlanning] = useState(false);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState<number[]>([]);
  async function load() { try { const data = await api<Overview>("/intelligence/overview"); setOverview(data); if (data.cashflow_source) setBudget((current) => ({ ...current, ...data.cashflow_source })); } catch (e) { setError(errorMessage(e)); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function allocate(e: FormEvent) { e.preventDefault(); setPlanning(true); setError(""); try { setResult(await api<AllocationResult>("/intelligence/allocate", { method: "POST", body: JSON.stringify({ ...budget, monthly_safety_buffer_cny: budget.monthly_safety_buffer_cny || "0", depth: "complex" }) })); setSaved([]); } catch (e) { setError(errorMessage(e)); } finally { setPlanning(false); } }
  async function saveRecommendation(item: AgentRecommendation, index: number) { await api("/intelligence/actions", { method: "POST", body: JSON.stringify({ ...item, title: item.action, source: "DECISION_STUDIO" }) }); setSaved((current) => [...current, index]); await load(); }
  async function updateAction(id: string, status: string) { await api(`/intelligence/actions/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(); }
  async function removeAction(id: string) { await api(`/intelligence/actions/${id}`, { method: "DELETE" }); await load(); }
  if (loading) return <><div className="page-head"><div><div className="eyebrow">WHITE FINANCIAL TWIN</div><h1>怀特决策舱</h1></div></div><Skeleton height={560} /></>;
  if (!overview) return <Card className="card-pad"><Empty title="决策舱暂时没有打开" body={error || "请稍后再试"} /></Card>;
  return <>
    <div className="page-head intelligence-head"><div><div className="eyebrow">WHITE FINANCIAL TWIN</div><h1>怀特决策舱</h1><p>用真实资产、现金流、目标和行动记录构建你的个人财务数字画像。</p></div><Badge tone="purple"><Orbit /> 可解释财务数字画像</Badge></div>
    {error ? <div className="inline-error"><CircleAlert />{error}</div> : null}
    <div className="twin-hero"><Card className="twin-score"><div className="twin-score-ring" style={{ "--score": `${Math.min(Number(overview.score), 100) * 3.6}deg` } as React.CSSProperties}><div><strong>{Number(overview.score).toFixed(0)}</strong><span>/ 100</span></div></div><div><Badge tone="purple">{overview.score_label}</Badge><h2>不是投资成绩，而是做决定时的底气</h2><p>{overview.score_explanation}</p><div className="twin-data-tags"><span>{overview.data_availability.snapshot_count} 个清算点</span><span>{overview.data_availability.goal_count} 个目标</span><span>{overview.data_availability.has_cashflow ? "现金流已接入" : "等待现金流"}</span></div></div></Card><Card className="twin-alerts"><div className="card-head"><div><h2>偏离雷达</h2><p>只提示真正改变决策的地方。</p></div><Activity /></div>{overview.alerts.length ? overview.alerts.map((item) => <div key={item.code}><Badge tone={item.level === "HIGH" ? "warning" : "purple"}>{item.level === "HIGH" ? "优先" : "留意"}</Badge><span><strong>{item.title}</strong><p>{item.detail}</p></span></div>) : <div className="all-calm"><Check /> 当前没有触发明显偏离</div>}</Card></div>
    <section className="twin-factors">{overview.factors.map((factor) => <Card key={factor.code}><div><span>{factor.name}</span><strong>{factor.score}<small> / {factor.max_score}</small></strong></div><b><i style={{ width: `${Math.min(Number(factor.score) / Number(factor.max_score) * 100, 100)}%` }} /></b><p>{factor.value}</p><small>{factor.interpretation}</small></Card>)}</section>
    <Card className="card-pad allocation-lab"><div className="card-head"><div className="card-title-row"><div className="card-icon"><BrainCircuit /></div><div><h2>多目标资金调度</h2><p>先由算法守住总额和期限，再让怀特复核优先顺序与取舍。</p></div></div><Badge tone="purple">不会重复使用月结余</Badge></div><form onSubmit={allocate}><div className="form-grid"><Field label="每月固定收入"><input inputMode="decimal" value={budget.monthly_income_cny} onChange={(e) => setBudget({ ...budget, monthly_income_cny: e.target.value })} required /></Field><Field label="每月固定支出"><input inputMode="decimal" value={budget.monthly_fixed_expenses_cny} onChange={(e) => setBudget({ ...budget, monthly_fixed_expenses_cny: e.target.value })} required /></Field><Field label="保留机动金"><input inputMode="decimal" value={budget.monthly_safety_buffer_cny} onChange={(e) => setBudget({ ...budget, monthly_safety_buffer_cny: e.target.value })} /></Field><Field label="调度策略"><select value={budget.strategy} onChange={(e) => setBudget({ ...budget, strategy: e.target.value })}><option value="BALANCED">平衡期限与可达性</option><option value="DEADLINE_FIRST">期限优先</option><option value="SMALLEST_GAP">先完成最接近的目标</option></select></Field></div><Button loading={planning}><Sparkles /> 生成真实调度方案</Button></form>
      {result ? <div className="allocation-result"><div className="allocation-result-metrics"><div><span>每月可分配</span><strong>{money(result.plan.monthly_available_cny)}</strong></div><div><span>已经安排</span><strong>{money(result.plan.monthly_allocated_cny)}</strong></div><div><span>仍留有余地</span><strong>{money(result.plan.monthly_unallocated_cny)}</strong></div><div><span>期限冲突</span><strong>{result.plan.deadline_conflict_count}</strong></div></div><div className="goal-allocation-list">{result.plan.allocations.map((item) => <div key={item.goal_id}><Target /><span><strong>{item.goal_name}</strong><small>还差 {money(item.gap_cny)} · 预计 {item.projected_months || "—"} 个月</small></span><b>{money(item.monthly_allocation_cny)} / 月</b><Badge tone={item.on_track === false ? "warning" : "purple"}>{item.on_track === false ? "需要调整" : item.on_track === true ? "按期可达" : "稳步推进"}</Badge></div>)}</div><div className="allocation-verdict"><Gauge /><strong>{result.agent.result.executive_summary}</strong></div><div className="decision-recommendations">{result.agent.result.recommendations.map((item, index) => <div key={`${item.action}-${index}`}><Badge tone={item.priority === "HIGH" ? "warning" : "purple"}>{item.priority}</Badge><strong>{item.action}</strong><p>{item.reason}</p><small>{item.review_trigger}</small><Button variant="ghost" disabled={saved.includes(index)} onClick={() => saveRecommendation(item, index)}><BookmarkCheck />{saved.includes(index) ? "已加入行动账本" : "加入行动账本"}</Button></div>)}</div></div> : null}
    </Card>
    <Card className="card-pad action-ledger"><div className="card-head"><div className="card-title-row"><div className="card-icon"><ListChecks /></div><div><h2>行动账本</h2><p>建议被接受后才进入这里，下次分析会参考执行状态。</p></div></div><Badge tone="purple">反馈闭环</Badge></div>{overview.actions.length ? <div className="ledger-list">{overview.actions.map((item) => <div className={`ledger-${item.status.toLowerCase()}`} key={item.id}><i /><div><Badge tone={item.priority === "HIGH" ? "warning" : "purple"}>{item.source}</Badge><strong>{item.title}</strong><p>{item.reason}</p><small>{item.review_trigger}</small></div><div>{item.status !== "DONE" ? <Button variant="ghost" onClick={() => updateAction(item.id, item.status === "DOING" ? "DONE" : "DOING")}>{item.status === "DOING" ? <Check /> : <Play />}{item.status === "DOING" ? "标记完成" : "开始执行"}</Button> : <Badge tone="purple"><Check /> 已完成</Badge>}<Button variant="ghost" onClick={() => updateAction(item.id, "SNOOZED")}><Pause /> 稍后</Button><button className="icon-button danger-text" onClick={() => removeAction(item.id)}><Trash2 /></button></div></div>)}</div> : <Empty title="行动账本还是空的" body="从怀特的建议、趋势复盘或本期重点中挑一项真正想做的事情。" />}</Card>
  </>;
}
export default function IntelligencePage() { return <Protected><IntelligenceContent /></Protected>; }
