export type Me = {id:string; email:string; role:string; totp_enabled:boolean; security_setup_required:boolean; region:string; model_preference:string; timezone:string; unread_notifications:number};
export type Totals = {assets_cny:string; liabilities_cny:string; net_worth_cny:string; liquid_assets_cny:string; restricted_assets_cny:string; investment_assets_cny:string; by_type:Record<string,string>; by_currency:Record<string,string>; type_percentages:Record<string,string>; currency_percentages:Record<string,string>};
export type AssetItem = {id:string; session_id:string; name:string; account_alias?:string|null; asset_type:string; category:string; original_currency:string; original_value:string; current_market_value?:string|null; cost_basis?:string|null; unrealized_pl?:string|null; quantity?:string|null; interest_rate?:string|null; maturity_date?:string|null; liquidity_level:string; is_liability:boolean; source:string; status:string; confidence?:string|null; value_cny?:string|null; fx_rate_to_cny?:string|null; notes?:string|null; metadata_json:Record<string,unknown>};
export type ClearingSession = {id:string; kind:string; status:string; revision_number:number; supersedes_id?:string|null; started_at:string; confirmed_at?:string|null; completeness:string; totals?:Totals; fx_snapshot?:Record<string,unknown>; comparison?:Record<string,unknown>; revision_reason?:string|null; items?:AssetItem[]};
export type SpendingProfile = {configured:boolean;source:string;monthly_income_cny:string;monthly_essential_expenses_cny:string;monthly_current_expenses_cny:string;emergency_months:string};
export type SpendingSnapshot = {
  ready:boolean; reason?:string; snapshot_id?:string; profile:SpendingProfile;
  safe_to_spend_cny?:string; reassess_above_cny?:string; free_cash_after_reserves_cny?:string; protected_cash_cny?:string;
  protection?:{emergency_reserve_cny:string;upcoming_90d_cny:string;committed_goal_cash_cny:string;debt_buffer_cny:string;risk_reserve_cny:string};
  risk?:{level:string;investment_pct:string;foreign_currency_pct:string};
  battery?:{before_pct:string;after_pct:string;before_label:string;after_label:string;current_lifestyle_months_before:string|null;current_lifestyle_months_after:string|null;essential_only_months_before:string|null;essential_only_months_after:string|null;without_selling_investments_months_before:string|null;without_selling_investments_months_after:string|null};
  simulation?:{amount_cny:string;cash_before_cny:string;cash_after_cny:string;net_worth_before_cny:string;net_worth_after_cny:string};
  verdict?:"DO_IT"|"ADJUST"|"WAIT";verdict_label?:string;suggested_max_budget_cny?:string;needs_investment_sale?:boolean;goal_delay_days?:number|null;
  regret_warnings?:string[];alternatives?:string[];calculation_note?:string;decision?:string;category?:string;planned_date?:string|null;
};
export type SpendingRuling = {id:string;decision:string;created_at:string;result:SpendingSnapshot;agent:{provider:string;model:string;result:{executive_summary?:string;analysis?:string[];recommendations?:Array<{action:string;reason:string;expected_impact:string;risk:string}>;alternatives?:string[]}}};
export type Dashboard = {has_snapshot:boolean; snapshot?:ClearingSession; totals?:Totals; next_clearing_at?:string|null; goals:Array<{id:string;name:string;target_cny:string;current_cny:string;progress_pct:string;gap_cny:string;due_date?:string|null}>; risks:Array<{level:string;code:string;title:string;detail:string}>; trend:Record<string,unknown>; spending:SpendingSnapshot; data_freshness?:Record<string,unknown>};
